name: Build and deploy ASP.NET Core app to Azure Web App - cut

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Publish .NET project
        run: dotnet publish -c Release -o publish

      - name: Upload publish folder
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: .

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4FF252B017CC41B8ADF57048EDF85B54 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D892F22BC1E64B00BCB239D05F7B2266 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B1178B6CBB84916B7096CFFAC55095A }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'cut'
          package: .
